[project]
name = "color-diffusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-image>=0.25.2",
    "sentence-transformers>=5.1.0",
    "torch>=2.8.0",
]
